services:

  ai:
    build:
      context: ./DroneWaste_ai
    container_name: dronewaste-ai
    ports:
      - "8000:8000"
    volumes:
      - ./DroneWaste_ai/model:/app/model   # model.pt persiste entre reinicios
    restart: unless-stopped

  backend:
    build:
      context: ./DroneWaste_back
    container_name: dronewaste-back
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./DroneWaste_front
      args:
        VITE_GOOGLE_MAPS_KEY: ${VITE_GOOGLE_MAPS_KEY}
        VITE_GEMINI_KEY: ${VITE_GEMINI_KEY}
        VITE_API_URL: http://localhost:8080
        VITE_AI_URL: http://localhost:8000
    container_name: dronewaste-front
    ports:
      - "5173:80"
    depends_on:
      - backend
      - ai
    restart: unless-stopped
